'use client';

import Link from 'next/link';
import { AlertTriangle, Brain, CheckCircle2, FileSearch, ShieldAlert } from 'lucide-react';
import { AppShell } from '@/components/layout/AppShell';
import { PageHeader } from '@/components/layout/PageHeader';
import { EvidenceTrail } from '@/components/triage/EvidenceTrail';
import { useDrillStore } from '@/store/useDrillStore';

export default function AlertsPage() {
  const { risk, telemetry, alertCount, acknowledgedAt, acknowledgeCurrentRisk } = useDrillStore();
  const hasActionableRisk = risk.riskLevel === 'high' || risk.riskLevel === 'critical';
  return <AppShell><PageHeader title="Alerts" description="Risk conditions, their supporting offset-well evidence, and acknowledgement history." /><div className="mx-auto max-w-5xl space-y-4">
    {hasActionableRisk ? <section className="overflow-hidden rounded-xl border border-orange-600/60 bg-orange-950/20 shadow-[0_0_20px_-10px_rgba(249,115,22,0.65)]" role="alert"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-orange-800/50 p-4"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-6 w-6 text-orange-400" /><div><p className="ops-eyebrow text-orange-300">{acknowledgedAt ? 'Acknowledged risk' : 'High risk'}</p><h2 className="mt-1 text-lg font-semibold text-white">{risk.predictedHazard}</h2><p className="mt-1 text-sm text-slate-300">{telemetry.measuredDepthM.toLocaleString()} m MD • {telemetry.currentFormation} • Risk score {risk.riskScore}/100</p></div></div><span className="rounded-full border border-orange-600/70 bg-orange-950 px-3 py-1 text-xs font-bold text-orange-200">{acknowledgedAt ? 'ACKNOWLEDGED' : 'ACTION REQUIRED'}</span></div><div className="grid gap-4 p-4 md:grid-cols-[1fr_auto]"><div><p className="text-sm font-semibold text-white">Operational context</p><p className="mt-1 text-sm leading-relaxed text-slate-300">{risk.immediateAction}</p><p className="mt-3 text-xs text-slate-400">Supporting evidence: {risk.offsetWellCitation}</p></div><div className="flex flex-wrap gap-2 md:flex-col"><Link href="/lessons?evidence=northwind" className="inline-flex items-center justify-center gap-1 rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-200"><FileSearch className="h-3.5 w-3.5" /> View evidence</Link><Link href={`/ai?prompt=${encodeURIComponent('Why was this alert generated? What evidence is relevant to the active depth?')}`} className="inline-flex items-center justify-center gap-1 rounded-lg border border-purple-700 px-3 py-2 text-xs font-semibold text-purple-200"><Brain className="h-3.5 w-3.5" /> Ask AI</Link>{!acknowledgedAt && <button onClick={acknowledgeCurrentRisk} className="inline-flex items-center justify-center gap-1 rounded-lg bg-orange-400 px-3 py-2 text-xs font-bold text-slate-950"><CheckCircle2 className="h-3.5 w-3.5" /> Acknowledge</button>}</div></div>{acknowledgedAt && <div className="border-t border-slate-800 bg-slate-950/30 px-4 py-3 text-xs text-emerald-300">Acknowledged in this demo session at {new Date(acknowledgedAt).toLocaleString()}. Alert count updated to {alertCount}.</div>}</section> : <section className="rounded-xl border border-slate-800 bg-slate-900/50 px-6 py-14 text-center"><ShieldAlert className="mx-auto h-8 w-8 text-emerald-400" /><h2 className="mt-3 text-lg font-semibold">No active alerts</h2><p className="mx-auto mt-2 max-w-md text-sm text-slate-400">Alerts appear here when threshold or historical-risk conditions become relevant to the active drilling context.</p></section>}
    <EvidenceTrail expandedByDefault />
    <section className="ops-panel p-4"><h2 className="text-sm font-semibold">Alert history</h2>{acknowledgedAt ? <p className="mt-2 text-sm text-slate-300">Current risk acknowledged at {new Date(acknowledgedAt).toLocaleString()}.</p> : <p className="mt-2 text-sm text-slate-400">No acknowledgement events in this session.</p>}</section>
  </div></AppShell>;
}
